[versions]
accompanist = "0.22.0-rc"
agp = "7.0.4"
android-compile = "31"
android-min = "21"
androidx-lifecycle = "2.4.0"
compose = "1.0.5"
compose-compiler = "1.1.0-rc02"
exercise = "0.10.0"
kable = "0.10.4"
kotlin = "1.6.10"
ksp = "1.6.10-1.0.2"
tuulbox = "5.1.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.4.0" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version = "compose" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.0" }
coroutines-macosx64 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-macosx64", version = "1.6.0-native-mt!!" }
exercise-annotations = { module = "com.juul.exercise:annotations", version.ref = "exercise" }
exercise-compile = { module = "com.juul.exercise:compile", version.ref = "exercise" }
kable = { module = "com.juul.kable:core", version.ref = "kable" }
stately = { module = "co.touchlab:stately-isolate", version = "1.2.1" }
tuulbox-coroutines = { module = "com.juul.tuulbox:coroutines", version.ref = "tuulbox" }
tuulbox-encoding = { module = "com.juul.tuulbox:encoding", version.ref = "tuulbox" }
tuulbox-logging = { module = "com.juul.tuulbox:logging", version.ref = "tuulbox" }

[bundles]
accompanist = [
    "accompanist-permissions",
]
compose = [
    "compose-activity",
    "compose-material",
    "compose-tooling",
    "compose-ui",
    "compose-viewmodel",
]

[plugins]
android-application = { id = "com.android.library", version.ref = "agp" }
java8 = { id = "net.mbonnin.one.eight", version = "0.2" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
