[versions]
agp = "4.1.3"
android-compile = "android-31"
android-min = "21"
androidx-lifecycle = "2.2.0"
exercise = "0.9.0"
kable = "0.9.2"
kotlin = "1.6.0"
ksp = "1.6.0-1.0.1"
tuulbox = "4.8.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity-ktx", version = "1.1.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.1.0" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.2.1" }
exercise-annotations = { module = "com.juul.exercise:annotations", version.ref = "exercise" }
exercise-compile = { module = "com.juul.exercise:compile", version.ref = "exercise" }
kable = { module = "com.juul.kable:core", version.ref = "kable" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.5.2" }
kotlinx-coroutines-macosx64 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-macosx64", version = "1.5.0-native-mt!!" }
material = { module = "com.google.android.material:material", version = "1.4.0" }
stately = { module = "co.touchlab:stately-isolate", version = "1.2.0" }
tuulbox-encoding = { module = "com.juul.tuulbox:encoding", version.ref = "tuulbox" }
tuulbox-logging = { module = "com.juul.tuulbox:logging", version.ref = "tuulbox" }

[bundles]
androidx = [ "androidx-appcompat", "androidx-recyclerview", "androidx-lifecycle-viewmodel", "androidx-lifecycle-livedata", "androidx-activity" ]

[plugins]
android-application = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
one-eight = { id = "net.mbonnin.one.eight", version = "0.2" }
