[versions]
accompanist = "0.23.0"
agp = "7.1.1"
android-compile = "31"
android-min = "21"
androidx-lifecycle = "2.4.1"
compose = "1.1.0"
compose-compiler = "1.1.0"
exercise = "0.10.0"
kable = "0.14.0"
kotlin = "1.6.10"
krayon = "0.8.2"
ksp = "1.6.10-1.0.3"
tuulbox = "5.1.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.4.0" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version = "compose" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.0" }
coroutines-macosx64 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-macosx64", version = "1.6.0-native-mt!!" }
exercise-annotations = { module = "com.juul.exercise:annotations", version.ref = "exercise" }
exercise-compile = { module = "com.juul.exercise:compile", version.ref = "exercise" }
kable = { module = "com.juul.kable:core", version.ref = "kable" }
krayon-axis = { module = "com.juul.krayon:axis", version.ref = "krayon" }
krayon-scale = { module = "com.juul.krayon:scale", version.ref = "krayon" }
krayon-selection = { module = "com.juul.krayon:selection", version.ref = "krayon" }
krayon-shape = { module = "com.juul.krayon:shape", version.ref = "krayon" }
krayon-view = { module = "com.juul.krayon:element-view", version.ref = "krayon" }
stately = { module = "co.touchlab:stately-isolate", version = "1.2.1" }
tuulbox-coroutines = { module = "com.juul.tuulbox:coroutines", version.ref = "tuulbox" }
tuulbox-encoding = { module = "com.juul.tuulbox:encoding", version.ref = "tuulbox" }
tuulbox-logging = { module = "com.juul.tuulbox:logging", version.ref = "tuulbox" }

[bundles]
accompanist = [
    "accompanist-permissions",
]
compose = [
    "compose-activity",
    "compose-material",
    "compose-tooling",
    "compose-ui",
    "compose-viewmodel",
]
krayon = [
    "krayon-axis",
    "krayon-scale",
    "krayon-selection",
    "krayon-shape",
    "krayon-view",
]

[plugins]
android-application = { id = "com.android.library", version.ref = "agp" }
java8 = { id = "net.mbonnin.one.eight", version = "0.2" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
