name: CI
on:
  pull_request:
  # Trigger on merges to `main` to allow `gradle/gradle-build-action` runs to write their caches.
  # https://github.com/gradle/gradle-build-action#using-the-caches-read-only
  push:
    branches:
      - main

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew assemble
      - run: ./gradlew check
