name: Webapp
on:
  pull_request:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  build:
    name: Browser Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew jsBrowserDistribution
